Created API and files to deploy to Heroku to test API
CodingPenguin/sentysis_flask pull request #1
Opened 2021-01-02 04:42 UTC by CodingPenguin

PLS APPROVE LIKE A BOSS

2021-01-02 05:05 UTC, lekosfmi requested changes

2021-01-02 05:05 UTC, lekosfmi commented on sentysis/sentysis.py
> +    return "<h1>WHAT'S UP LOSER</h1>"
LOL

2021-01-02 05:05 UTC, lekosfmi commented on sentysis/sentysis.py
> +@app.route('/api/ytUrls', methods=['GET', 'POST'])
You don't need `'GET'`

2021-01-05 14:22 UTC, CodingPenguin commented on sentysis/sentysis.py
> +@app.route('/api/ytUrls', methods=['GET', 'POST'])
Ok yah got it

2021-01-05 14:23 UTC, merged

2021-01-05 17:12 UTC, lekosfmi commented
Next time don't merge until I approve. Thanks!